/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Sniffer */

#ifndef _Included_Sniffer
#define _Included_Sniffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Sniffer
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Sniffer_run
  (JNIEnv *, jobject);

/*
 * Class:     Sniffer
 * Method:    getPrintBuffer
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_Sniffer_getPrintBuffer
  (JNIEnv *, jobject);

/*
 * Class:     Sniffer
 * Method:    getStatistics
 * Signature: ()LStatistics;
 */
JNIEXPORT jobject JNICALL Java_Sniffer_getStatistics
  (JNIEnv *, jobject);

/*
 * Class:     Sniffer
 * Method:    getPacketsFromBuffer
 * Signature: (I)[LIpv4Header;
 */
JNIEXPORT jobjectArray JNICALL Java_Sniffer_getPacketsFromBuffer
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
